#!/bin/bash

echo "Stopping..."
sudo stop hots-counter
echo "Stopped... updating from git..."
git pull
cd public/
echo "Running bower install..."
bower install
cd ../
echo "Running grunt..."
grunt
echo "Starting site..."
sudo start hots-counter
echo "Changes deployed"
