#!/bin/bash

echo "Stopping..."
sudo stop hots-counter
echo "Stopped... updating from git..."
git pull https://github.com/Evertras/HotsCounter.git
cd public/
# echo "Running npm install..."
# npm install
# echo "Running bower install..."
# bower install
cd ../
echo "Running grunt..."
grunt
echo "Starting site..."
sudo start hots-counter
cowsay "Changes deployed"
